### ISSUE TITLE
Error while call Runner()

### ISSUE THREAD

**Issue by houzw** [giswqs/whitebox#1]
* whitebox version: latest
* Python version: 3.4
* Operating System: windows 10

### Description

D:\Python34\python3.exe F:/demospace/whitebox/run.py
Traceback (most recent call last):
  File "F:/demospace/whitebox/run.py", line 7, in <module>
    whitebox.Runner()
  File "D:\Python34\lib\site-packages\whitebox\wb_runner.py", line 1129, in Runner
    wbr = WbRunner(tool_name)
  File "D:\Python34\lib\site-packages\whitebox\wb_runner.py", line 729, in __init__
    for filename in glob.iglob('**/*', recursive=True):
TypeError: iglob() got an unexpected keyword argument 'recursive'

### What I Did

```python
import whitebox
whitebox.Runner()
```

**Comment by giswqs** [comment]
Thank you for reporting the issue! I have not tested the package in Python 3.4 before. It turns out the the  recursive parameter for iglob() was added in Python 3.5. Check this [link](https://stackoverflow.com/questions/35715353/glob-iglob-to-find-all-txt-files-in-all-sub-directories-yields-error). I would suggest you use [conda](https://github.com/giswqs/whitebox#installation) to install Python 3.5 or newer, which should not have this problem.

**Comment by houzw** [comment]
yes, it works under python 3.5
